{
 "title": "Benchmark Result",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "RPS over 3 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(echo_requests_total{url=\"/test/:tool\"}[3s])",
     "legendFormat": "{{test_tool}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(container_cpu_user_seconds_total{image=~\"loadtest-.*\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image=~\"loadtest-tools-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "averate RPS by test tools",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(rate(echo_requests_total{url=\"/test/:tool\"}[5s]) != 0) by (test_tool)",
     "legendFormat": "{{test_tool}}"
    }
   ]
  },
  {
   "title": "total request by test tools",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "echo_requests_total", "legendFormat": "{{test_tool}}" }
   ]
  }
 ]
}