{
 "title": "benchmark",
 "time": { "from": "2024-03-01T06:45:35.040Z", "to": "2024-03-01T06:56:47.013Z" },
 "panels": [
  {
   "title": "RPS over 3 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(echo_requests_total{url=\"/test/:tool\"}[3s])",
     "legendFormat": "{{test_tool}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image=~\"loadtest-.*\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image=~\"loadtest-tools-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "averate RPS by test tools",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(rate(echo_requests_total{url=\"/test/:tool\"}[5s]) != 0) by (test_tool)",
     "legendFormat": "{{test_tool}}"
    }
   ]
  }
 ]
}