{
 "title": "Monitor Target Endpoint",
 "time": { "from": "2024-02-29T04:56:20.837Z", "to": "2024-02-29T04:59:28.168Z" },
 "panels": [
  {
   "title": "number of goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"target:3000\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RPS over 5 second interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(myapp_requests_total{url!=\"/metrics\"}[5s])",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Request duration distribution",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "myapp_request_duration_seconds_bucket{url=\"/hello\"}",
     "legendFormat": "{{method}} {{url}} {{le}} seconds"
    }
   ]
  }
 ]
}